language: python
python:
  - "2.7"
install: 
  - pip install --use-mirrors pyparsing
  - pip install --use-mirrors matplotlib
  - pip install natsort
  - pip install matplotlib
  - pip install scipy
  - pip install numpy
script: nosetests
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install libblas-dev
  - sudo apt-get install liblapack-dev
  - sudo apt-get install gfortran
script: nosetests
after_success:
  - coveralls